### DISCUSSION TITLE
Handling sibling sessions for different modalities

### DISCUSSION THREAD

**Discussion by tclose** [ArcanaFramework/arcana#159] [Ideas]
The topic of how to handle multiple XNAT sessions for a single subject corresponding to different modalities in the Arcana data model came up during a discussion with @hachterberg the other day. For example, if each subject has two MRI sessions containing brain scans and a single session to collect cardiac ultrasound  collected at a different timepoint.

This is a bit of a tricky case as Arcana currently assumes that each session contains equivalent data, so there would be three ways to try to treat such cases:

1. Extend the concept of data spaces to include "dimensions" containing complementary, rather than equivalent, data and add a "modality" dimension to the dataset.
    * Pros:
        * allows individual modality sessions to be excluded using existing exclusion criteria logic
        * fits in with the concept of a single XNAT session being a point in sample grid of the data space
    * Cons:
        * Extending data spaces can be a bit complicated when trying to reuse existing analysis classes
        * Would need to match up sessions of differing modalities to the same timepoints
        * Not clear handle the case where the number of different modality sessions differ within a subject (as in the case above 2 neuro + one cardiac)
2. Extend the concept of the file-set "path" to include the session modality
    * Pros:
        * this would align with how data is laid out in BIDS format
        * wouldn't need to mess around with the "space" of the dataset
        * easy to combine multi-modality data
    * Cons:
        * Also not clear how to handle the case where the number of modality sessions differ within a subject
            * would probably need to match the cardiac to one of the neuro and leave the other without
        * would mess with the syntax of paths, making them relative to an upstream node rather than just the node they are stored in
3. Split the different modalities into separate "sub-sets", you could then define which axes of the data space are shared between the subsets (e.g. groups + subjects, but not sessions). This is my favoured approach at this stage
    * Pros:
        * Would enable analyses of each modality to be performed separately using existing analyses
        * Could handle varying number of sessions per modality
        * Could start off by just defining two datasets and manually mapping columns between them
    * Cons:
        * A bit more effort than the paths approach to combine multi-modality data

**Comment by tclose** [comment]
I realised that Option 3) could also be used to handle another hard-to-handle case, where there are multiple tasks/runs of a type of functional scan in a session. In this case, an additional dimension could be added to the data space, (e.g. "task" or "run") and "partitions" (subsets in the parlance of the above post) used to manually assign different "task-ID"s to each, e.g.

```yaml
name: example
store-version: 1.0.0
metadata:  # Primarily required for BIDS export
  title: A sample dataset with subjects with high motion excluded
  acknowledgements: null
  authors:
  - name: Thomas G. Close
    email: thomas.close@sydney.edu.au
  doi: null
  ethics_approvals: []
  funding: []
  generated_by:
  - code_url: https://github.com/ArcanaFramework/arcana
    container: null
    description: dataset definition was generated by Arcana CLI
    name: arcana
    version: 0.9.8
  how_to_acknowledge: see licence
  license: CC0
  description: >-
    this dataset is an example to demonstrate all potential features of an Arcana dataset
    definition
  references: []
  row_keys: []
  sources: []
  type: derivative
grid:
  space: /clinical  # This will be extended to include the "task" axis"
  hierarchy:  # NB: this hierarchy is fixed for project data trees in XNAT
  - subject
  - session
  id_patterns:
    group: "subject::(\\w+)\\d+"
    member: "subject::\\w+(\\d+)"
    visit: "visit_#session:visit_id:VISIT(\\d+)#"
  include:
    visit:
    - 01
    - 02
  exclude:
    subject:
    - CONT04
    - TEST11
  sources:
    anat/t1w:
      datatype:
        format: medimage/dicom-set
        classifiers:
          species: human
          region: brain
          modality: mri
          contrast: t1w
      is_regex: true
      order: -1  # select last scan matching ".*mprage.*" in session
      path: "*.mprage.*"
      quality_threshold: usable
      row_frequency: session
      metadata_schema: null
    anat/flair:
      datatype:
        format: medimage/dicom-set
        classifiers:
          species: human
          region: brain
          modality: mri
          contrast: flair
      is_regex: false
      order: null
      path: ".*flair.*"
      quality_threshold: usable
      row_frequency: session
      metadata_schema: null
  sinks:
    brain_mask:
      datatype:
        format: medimage/nifti-gz-x
      path: brain_mask@
      row_frequency: session
    brain_template:
      datatype:
        format: medimage/nifti-gz-x
      path: brain-template@
      row_frequency: dataset
  partitions:
    bloods:
      free_axes:
      - visit  # Bloods are only collected in a single visit whereas there are >2 MRI sessions
      selection:
        session: ".*_BLD"  # matches pecial sessions under each subject named *_BLD
      sources:
        hematocrit:
          path: "HAEM.*"
          datatype:
            format: text/csv
          row_frequency: session
        glucose:
          path: "GLU.*"
          datatype:
            format: text/csv
          row_frequency: session
    rest:
      constant_ids:
        task: rest  # the "task" ID of the "session_task" row (i.e. an individual task within a session)
      sources:
        anat/bold:
          path: ".*bold.*"
          order: 0  # First fMRI acquisition is assumed to be REST
          datatype:
            format: medimage/dicom-set
            classifiers:
              species: human
              region: brain
              modality: mri
              contrast: bold
          row_frequency: session_task
          quality_threshold: usable
    finger_tapping:
      constant_ids:
        task: fingertap
      sources:
        anat/bold:
          path: ".*bold.*"
          order: 1  # Second fMRI acquisition is assumed to be a finger-tapping task
          datatype:
            format: medimage/dicom-set
            classifiers:
              species: human
              region: brain
              modality: mri
              contrast: bold
          row_frequency: session_task
          quality_threshold: usable
    recall:
      constant_ids:
        task: recall
      sources:
        anat/bold:
          path: ".*bold.*"
          order: 2  # Third fMRI acquisition is assumed to be a finger-tapping task
          datatype:
            format: medimage/dicom-set
            classifiers:
              species: human
              region: brain
              modality: mri
              contrast: bold
          row_frequency: session_task
          quality_threshold: usable
applied:
  pipelines: {}
  analyses: {}
pkg_versions:
  arcana: 0.9.8
  fileformats: 0.5.0
```
